/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppOrderRoomRouteImport } from './routes/_app.order-room'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientsRouteImport } from './routes/_app.clients'
import { Route as AppCashierRouteImport } from './routes/_app.cashier'
import { Route as AppDeliveriesIndexRouteImport } from './routes/_app.deliveries.index'
import { Route as AppDeliveriesNewRouteImport } from './routes/_app.deliveries.new'
import { Route as AppDeliveriesIdRouteImport } from './routes/_app.deliveries.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderRoomRoute = AppOrderRoomRouteImport.update({
  id: '/order-room',
  path: '/order-room',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppCashierRoute = AppCashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesIndexRoute = AppDeliveriesIndexRouteImport.update({
  id: '/deliveries/',
  path: '/deliveries/',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesNewRoute = AppDeliveriesNewRouteImport.update({
  id: '/deliveries/new',
  path: '/deliveries/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesIdRoute = AppDeliveriesIdRouteImport.update({
  id: '/deliveries/$id',
  path: '/deliveries/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof AppCashierRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/order-room': typeof AppOrderRoomRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/deliveries/$id': typeof AppDeliveriesIdRoute
  '/deliveries/new': typeof AppDeliveriesNewRoute
  '/deliveries/': typeof AppDeliveriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cashier': typeof AppCashierRoute
  '/clients': typeof AppClientsRoute
  '/dashboard': typeof AppDashboardRoute
  '/order-room': typeof AppOrderRoomRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/users': typeof AppUsersRoute
  '/deliveries/$id': typeof AppDeliveriesIdRoute
  '/deliveries/new': typeof AppDeliveriesNewRoute
  '/deliveries': typeof AppDeliveriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/cashier': typeof AppCashierRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/order-room': typeof AppOrderRoomRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/deliveries/$id': typeof AppDeliveriesIdRoute
  '/_app/deliveries/new': typeof AppDeliveriesNewRoute
  '/_app/deliveries/': typeof AppDeliveriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cashier'
    | '/clients'
    | '/dashboard'
    | '/order-room'
    | '/products'
    | '/reports'
    | '/settings'
    | '/users'
    | '/deliveries/$id'
    | '/deliveries/new'
    | '/deliveries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cashier'
    | '/clients'
    | '/dashboard'
    | '/order-room'
    | '/products'
    | '/reports'
    | '/settings'
    | '/users'
    | '/deliveries/$id'
    | '/deliveries/new'
    | '/deliveries'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/cashier'
    | '/_app/clients'
    | '/_app/dashboard'
    | '/_app/order-room'
    | '/_app/products'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/users'
    | '/_app/deliveries/$id'
    | '/_app/deliveries/new'
    | '/_app/deliveries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order-room': {
      id: '/_app/order-room'
      path: '/order-room'
      fullPath: '/order-room'
      preLoaderRoute: typeof AppOrderRoomRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cashier': {
      id: '/_app/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof AppCashierRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries/': {
      id: '/_app/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof AppDeliveriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries/new': {
      id: '/_app/deliveries/new'
      path: '/deliveries/new'
      fullPath: '/deliveries/new'
      preLoaderRoute: typeof AppDeliveriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries/$id': {
      id: '/_app/deliveries/$id'
      path: '/deliveries/$id'
      fullPath: '/deliveries/$id'
      preLoaderRoute: typeof AppDeliveriesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCashierRoute: typeof AppCashierRoute
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrderRoomRoute: typeof AppOrderRoomRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsersRoute: typeof AppUsersRoute
  AppDeliveriesIdRoute: typeof AppDeliveriesIdRoute
  AppDeliveriesNewRoute: typeof AppDeliveriesNewRoute
  AppDeliveriesIndexRoute: typeof AppDeliveriesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCashierRoute: AppCashierRoute,
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOrderRoomRoute: AppOrderRoomRoute,
  AppProductsRoute: AppProductsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsersRoute: AppUsersRoute,
  AppDeliveriesIdRoute: AppDeliveriesIdRoute,
  AppDeliveriesNewRoute: AppDeliveriesNewRoute,
  AppDeliveriesIndexRoute: AppDeliveriesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
